### ISSUE TITLE
AppImage does not integrate into the system

### ISSUE THREAD

**Issue by tiotrom** [durasj/webamp-desktop#12]
First of all thank you for bringing back some really cool old memories :)
Now, usually with AppImageLauncher you can integrate an appimage simply into the system. But for this appimage it simply does not work. It only works to launch the app itself and that's pretty much it. Is this something to do with webamp itself? 
Cheers!

**Comment by durasj** [comment]
Hi @tiotrom, first of all, I'm so sorry I've missed this issue and thank you very much for giving this a try :)

I can take a look at your issue, what OS do you please use so I could try to reproduce it on the live image? I assume it'll be something with the way we package the app via [electron-builder](https://github.com/electron-userland/electron-builder). There is also .deb that you can find here https://github.com/durasj/webamp-desktop/releases/tag/v0.3.0 if your distribution supports it (Debian and it's derivatives AFAIK).

There is a ton of other stuff around webamp you can take a look at if you are interested like this [huge list of skins](https://blog.archive.org/2018/10/02/dont-click-on-the-llama/) or this trippy Milkdrop Visualizer [Butterchurn](https://github.com/jberg/butterchurn).

**Comment by tiotrom** [comment]
No worries adn thanks for replying. The August version works! So that's great! I was using Manjaro Gnome ;) - I'd love to see this in AUR too. Cheers!
