### ISSUE TITLE
Failed on Windows 10 Command Prompt

### ISSUE THREAD

**Issue by lavanyadeepak** [durasj/webamp-desktop#17]
C:\LavanyaDeepak\Personal\webamp-desktop>yarn start
yarn run v1.22.10
$ yarn run build && electron .
$ yarn run copy && yarn build:src
$ cp -r ./bundled/* ./dist
'cp' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by durasj** [comment]
Please use [Git Bash](https://git-scm.com/) on Windows. Scripts here are not designed for Windows's `cmd`.

**Comment by lavanyadeepak** [comment]
Thank you @durasj . That worked fine. Just a quick question. Is it possible to disable the browser toolbar that automatically opens up?

**Comment by durasj** [comment]
Glad to hear you got it running. Yes, the easiest way to do that would be to comment this line out https://github.com/durasj/webamp-desktop/blob/master/main.js#L13 or to set `ELECTRON_IS_DEV=0` env variable in the start script, so it would become `yarn run build && ELECTRON_IS_DEV=0 electron .`.
