### ISSUE TITLE
Running appimage doesn't seem to do anything

### ISSUE THREAD

**Issue by stuaxo** [durasj/webamp-desktop#8]
Hi,
   On Ubuntu 18.10 I ran the app image, it just quit immediately with seemingly nothing happening.

Cheers
S

**Comment by durasj** [comment]
Hi @stuaxo,

I'll download the daily build of 18.10 and try it. In the meantime, you can try to use the [.deb package](https://github.com/durasj/webamp-desktop/releases/download/v0.3.0/webamp-desktop_0.3.0_amd64.deb).

Thanks

**Comment by durasj** [comment]
Hi @stuaxo,

I am unable to reproduce on the latest daily build of 18.10. Here is all I'm doing:
```
wget https://github.com/durasj/webamp-desktop/releases/download/v0.3.0/webamp-desktop-0.3.0-x86_64.AppImage
chmod +x ./webamp-desktop-0.3.0-x86_64.AppImage
./webamp-desktop-0.3.0-x86_64.AppImage
```

As default ubuntu:ubuntu user.

**Comment by stuaxo** [comment]
That worked .. not sure what I was doing before.

Is the milkdrop integrated in this version ?

**Comment by durasj** [comment]
Maybe you forgot to make it executable? Either way glad you got it working!

Milkdrop is not there yet but soon will thanks to the work on the upstream webamp project.
